snorby/config/routes.rb
Snorby::Application.routes.draw do
  
  get "restart/index"
  get "network/show"

  resources :rules do
    collection do
    end
  end

  resources :tcpdumps do
    collection do
      
    end
  end

  resources :net_flows do
    collection do
    end
  end

  resources :logs do
    collection do
	get :export
        get :backup
	get :showbak
	get :recovery
	get :delete
	get :empty
    end
  end

  resources :lookups

  # This feature is not ready yet
  # resources :notifications

  resources :jobs do
    member do
      get :last_error
      get :handler
    end
  end

  resources :classifications

  devise_for :users, :path_names => { :sign_in => 'login', 
    :sign_out => 'logout', 
    :sign_up => 'register' }, :controllers => { 
      :registrations => "registrations",
      :sessions => "sessions", 
      :passwords => 'passwords'
    } do
    get "/login" => "devise/sessions#new"
    get '/logout', :to => "devise/sessions#destroy"
    get '/reset/password', :to => "devise/passwords#edit"
  end

  root :to => "page#dashboard"

  resources :sensors do


    collection do
      get :agent_list
    end
  end

  resources :settings do
    collection do
      get :restart_worker
      get :start_sensor_cache
      get :start_daily_cache
      get :start_geoip_update
      get :start_worker
      get :start_sys_status
    end
  end

  resources :signatures do

    collection do
      get :search
    end
    
  end

  resources :severities do
  end
  
  match '/restart', :controller => 'restart', :action => 'index'
  match '/restart/update', :controller => 'restart', :action => 'update'
  match '/time', :controller => 'time', :action => 'index'
  match '/time/update', :controller => 'time', :action => 'update'
  match '/time/get_time', :controller => 'time', :action => 'get_time'
  match '/network', :controller => 'network', :action => 'show'
  match '/network/edit', :controller => 'network', :action => 'edit'
  match '/network', :controller => 'network', :action => 'update'
  match '/dashboard', :controller => 'Page', :action => 'dashboard'
  match '/search', :controller => 'Page', :action => 'search'
  match '/results', :controller => 'Page', :action => 'results'
  match '/force/cache', :controller => "Page", :action => 'force_cache'
  match '/cache/status', :controller => "Page", :action => 'cache_status'
  match '/search/json', :controller => "Page", :action => 'search_json'
  match '/syslogconf/', :controller => "syslogconf", :action => 'index'
  match '/syslogconf/update', :controller => "syslogconf", :action => 'update'
  match '/tcpdump/start', :controller => "tcpdumps", :action => 'start'
  match '/tcpdump/stop', :controller => "tcpdumps", :action => 'stop'
  match '/tcpdump/sendfile', :controller => "tcpdumps", :action => 'sendfile'
 

  resources :saved_searches, :path => "/saved/searches" do
    
    collection do
      post :title
      post :update
    end

    member do
      get :view
      post :update
    end
  end

  match ':controller(/:action(/:sid/:cid))', :controller => 'Events'

  resources :asset_names do
    member do
      delete :remove
    end

    collection do
      post :add
      get :lookup
      post :bulk_upload
      get 'get_bulk_upload', action: :get_bulk_upload, as: 'get_bulk_upload'
    end
  end

  resources :events do
    
    resources :notes do
      
    end
    
    collection do
      get :sessions
      get :view
      get :create_mass_action
      post :mass_action
      get :create_email
      post :email
      get :hotkey
      post :export
      get :lookup
      get :rule
      get :packet_capture
      get :history
      post :classify
      post :classify_sessions
      post :mass_update
      get :queue
      post :favorite
      get :last
      get :since
      get :activity
      get :download
    end
    
  end
  
  resources :repositories do
    
    collection do
      get :test
    end

  end

  resources :notes

  resources :users do
    collection do
      post :toggle_settings
      post :remove
      post :add
    end
  end

  resources :page do
    collection do
      get :search
      get :results
    end
  end

end

snorby/app/models/log.rb
require 'netaddr'
require 'snorby/model/counter'

class Log

  include DataMapper::Resource

  property :id, Serial

  property :optime, String
  property :ip, String
  property :username, String
  property :opobject, String
  property :opdetail, String
  
  def self.empty
    sql="delete from logs;"
    db_execute(sql)
  end

end

snorby/app/controllers/logs_controller.rb
#encoding:utf-8
class LogsController < ApplicationController
  require 'csv'
  require 'find'
  # GET /logs
  # GET /logs.json
  respond_to :html, :xml, :json, :js, :csv

  
  def index
    @logs ||= Log.all.page(params[:page].to_i, :per_page => @current_user.per_page_count, :order => [:id.desc])
    
    respond_to do |format|
      format.html {render :layout => true}
      format.js
    end
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
    @log = Log.get(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @log }
    end
  end

  # GET /logs/new
  # GET /logs/new.json
  def new
    @log = Log.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @log }
    end
  end

  # GET /logs/1/edit
  def edit
    @log = Log.get(params[:id])
  end

  # POST /logs
  # POST /logs.json
  def create
    @log = Log.new(params[:log])
    @time=Time.now
    @log[:optime]=@time
    @log[:ip]="test"
    @log[:username]="suncle"
    @log[:opobject]="login"
    @log[:opdetail]="login s"
    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.' }
        format.json { render json: @log, status: :created, location: @log }
      else
        format.html { render action: "new" }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /logs/1
  # PUT /logs/1.json
  def update
    @log = Log.get(params[:id])

    respond_to do |format|
      if @log.update(params[:log])
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log = Log.get(params[:id])
    @log.destroy

    respond_to do |format|
      format.html { redirect_to logs_url }
      format.json { head :ok }
    end
  end

  #导出为csv文件
  def export
     @log =Log.find(:all)
     head = 'EF BB BF'.split(' ').map{|a|a.hex.chr}.join()
     csv_string = CSV.generate do |csv|
        csv << ["\xEF\xBB\xBFID","操作时间","用户","IP","操作对象","操作结果"]
        @log.each do |l|
          csv << [l.id,l.optime,l.username,l.ip,l.opobject,l.opdetail]
        end
      end
      send_data csv_string,
		:type=>'text/csv; charset=utf-8; header=present',  
                :disposition => "attachment; filename=log_export.csv"
    @log = Log.new
    time = Time.new
	@log[:optime] = time.strftime("%Y-%m-%d %H:%M:%S")
    @log[:ip]=request.remote_ip
    @log[:username]=@current_user
    @log[:opobject]="导出日志"
    @log[:opdetail]="导出成功"
    @log.save
  end

  #日志备份
  def backup
     exec=`sh #{Rails.root}/shell/logs_backup.sh`
    @log = Log.new
    time = Time.new
	@log[:optime] = time.strftime("%Y-%m-%d %H:%M:%S")
    @log[:ip]=request.remote_ip
    @log[:username]=@current_user
    @log[:opobject]="备份日志"
    @log[:opdetail]="备份成功"
    @log.save
     redirect_to :action => 'showbak'
  end

  def showbak
     @filename=[]
     Dir.foreach("#{Rails.root}/public/logsbackup") do |file|
        if file !="."and file !=".."
           @filename << file
        end 
     end
     @filename=@filename.sort.reverse
  end

  #日志恢复
  def recovery
    #filename = "logs_backup20150313104717.sql"
    @filename = params[:filename]
    exec=`sh #{Rails.root}/shell/logs_recovery.sh #{@filename}`
    @log = Log.new
    time = Time.new
	@log[:optime] = time.strftime("%Y-%m-%d %H:%M:%S")
    @log[:ip]=request.remote_ip
    @log[:username]=@current_user
    @log[:opobject]="恢复日志"
    @log[:opdetail]="恢复成功"
    @log.save
    redirect_to :action => 'index'
  end

  #删除备份
  def delete
    @filename = params[:filename]
    exec=`sh #{Rails.root}/shell/logsbak_delete.sh #{@filename}`
    @log = Log.new
    time = Time.new
	@log[:optime] = time.strftime("%Y-%m-%d %H:%M:%S")
    @log[:ip]=request.remote_ip
    @log[:username]=@current_user
    @log[:opobject]="删除日志备份"
    @log[:opdetail]="删除日志备份成功"
    @log.save
    redirect_to :action => 'showbak'
  end

  #清空日志
  def empty
    Log.empty
    @log = Log.new
    time = Time.new
	@log[:optime] = time.strftime("%Y-%m-%d %H:%M:%S")
    @log[:ip]=request.remote_ip
    @log[:username]=@current_user
    @log[:opobject]="清空日志"
    @log[:opdetail]="清空日志成功"
    @log.save
    redirect_to :action => 'index'
  end

end

snorby/app/helpers/logs_helper.rb
module LogsHelper
end

snorby/app/views/logs/_log.html.erb
 <tr>
	<td class='id first'><%= log.id %></td>
	
	<td class='optime'><%= log.optime %></td>
	
	<td class='username'><%= log.username %></td>
	<td class='ip'><%= log.ip %></td>
	
	<td class='opobject'><%= log.opobject %></td>
	
	<td class='opdetail'><%= log.opdetail %></td>	
</tr>

snorby/app/views/logs/_logs.html.erb
<div id="logs"  class='boxit'>

	<table class='default' border="0" cellspacing="0" cellpadding="0">
		<tr>		
			<th>ID</th>
			<th>时间</th>
			<th>用户</th>
			<th>IP</th>
			<th>操作</th>
			<th>操作结果</th>
		</tr>
		<tbody class='logs'>
			<%= render @logs %>
		</tbody>
	</table>
	
	<%= pager(@logs, request.fullpath) %>
</div>

snorby/app/views/logs/_menu.html.erb
	<%= drop_down_for('日志管理', 'icons/filter.png', 'options') do %>				
                
		<%= link_to "导出日志",export_logs_path %>
		<%= link_to "备份日志",backup_logs_path,confirm: '确认备份日志到服务器?' %>
		<%= link_to "查看备份",showbak_logs_path %>
		<%= link_to "清空日志",empty_logs_path,confirm: '确认清空所有日志?' %>
	
	<% end %>

snorby/app/views/logs/index.html.erb
	<%= title "系统日志" do -%>
			<%= render :partial => 'logs/menu' %>
		<% end %>

<div id="logs"  class='boxit'>

	<table class='default' border="0" cellspacing="0" cellpadding="0">
		<tr>		
			<th>ID</th>
			<th>时间</th>
			<th>用户</th>
			<th>IP</th>
			<th>操作</th>
			<th>操作结果</th>
		</tr>
		<tbody class='logs'>
			<%= render @logs %>
		</tbody>
	</table>
	
	<%= pager(@logs, request.fullpath) %>
</div>

snorby/app/views/logs/index.js.erb
$('div#logs').replaceWith("<%= escape_javascript(render(:partial => 'logs/logs', :locals => { :logs => @logs })) %>");
flash();

snorby/app/views/logs/showbak.html.erb
        <%= title "备份文件列表" do -%>
                        <%= render :partial => 'logs/menu' %>
                <% end %>

<div id="users" class='grid_12 page boxit'>
	
	<table class='default' border="0" cellspacing="0" cellpadding="0">
		<tr>
			<th>备份文件名</th>
			<th>恢复日志</th>
			<th>删除备份</th>
		</tr>
	<tbody class='logs'>
	
	<% @filename.each do |f| %>
	        <tr>
  			<td ><%= f %> </td>
			<td><%= link_to("恢复备份",{:controller => 'logs',:action => 'recovery',:filename => f, :class => "btn"})%></td>
			<td><%= link_to("删除备份",{:controller => 'logs',:action => 'delete',:filename => f, :class => "btn"},confirm: '确认删除本条备份?')%></td>
		</tr>
	<% end %>
		</tbody>
	</table>


	
	
</div>