snorby/config/routes.rb
Snorby::Application.routes.draw do
  
  get "restart/index"
  get "network/show"

  resources :rules do
    collection do
    end
  end

  resources :tcpdumps do
    collection do
      
    end
  end

  resources :net_flows do
    collection do
    end
  end

  resources :logs do
    collection do
	get :export
        get :backup
	get :showbak
	get :recovery
	get :delete
	get :empty
    end
  end

  resources :lookups

  # This feature is not ready yet
  # resources :notifications

  resources :jobs do
    member do
      get :last_error
      get :handler
    end
  end

  resources :classifications

  devise_for :users, :path_names => { :sign_in => 'login', 
    :sign_out => 'logout', 
    :sign_up => 'register' }, :controllers => { 
      :registrations => "registrations",
      :sessions => "sessions", 
      :passwords => 'passwords'
    } do
    get "/login" => "devise/sessions#new"
    get '/logout', :to => "devise/sessions#destroy"
    get '/reset/password', :to => "devise/passwords#edit"
  end

  root :to => "page#dashboard"

  resources :sensors do


    collection do
      get :agent_list
    end
  end

  resources :settings do
    collection do
      get :restart_worker
      get :start_sensor_cache
      get :start_daily_cache
      get :start_geoip_update
      get :start_worker
      get :start_sys_status
    end
  end

  resources :signatures do

    collection do
      get :search
    end
    
  end

  resources :severities do
  end
  
  match '/restart', :controller => 'restart', :action => 'index'
  match '/restart/update', :controller => 'restart', :action => 'update'
  match '/time', :controller => 'time', :action => 'index'
  match '/time/update', :controller => 'time', :action => 'update'
  match '/time/get_time', :controller => 'time', :action => 'get_time'
  match '/network', :controller => 'network', :action => 'show'
  match '/network/edit', :controller => 'network', :action => 'edit'
  match '/network', :controller => 'network', :action => 'update'
  match '/dashboard', :controller => 'Page', :action => 'dashboard'
  match '/search', :controller => 'Page', :action => 'search'
  match '/results', :controller => 'Page', :action => 'results'
  match '/force/cache', :controller => "Page", :action => 'force_cache'
  match '/cache/status', :controller => "Page", :action => 'cache_status'
  match '/search/json', :controller => "Page", :action => 'search_json'
  match '/syslogconf/', :controller => "syslogconf", :action => 'index'
  match '/syslogconf/update', :controller => "syslogconf", :action => 'update'
  match '/tcpdump/start', :controller => "tcpdumps", :action => 'start'
  match '/tcpdump/stop', :controller => "tcpdumps", :action => 'stop'
  match '/tcpdump/sendfile', :controller => "tcpdumps", :action => 'sendfile'
 

  resources :saved_searches, :path => "/saved/searches" do
    
    collection do
      post :title
      post :update
    end

    member do
      get :view
      post :update
    end
  end

  match ':controller(/:action(/:sid/:cid))', :controller => 'Events'

  resources :asset_names do
    member do
      delete :remove
    end

    collection do
      post :add
      get :lookup
      post :bulk_upload
      get 'get_bulk_upload', action: :get_bulk_upload, as: 'get_bulk_upload'
    end
  end

  resources :events do
    
    resources :notes do
      
    end
    
    collection do
      get :sessions
      get :view
      get :create_mass_action
      post :mass_action
      get :create_email
      post :email
      get :hotkey
      post :export
      get :lookup
      get :rule
      get :packet_capture
      get :history
      post :classify
      post :classify_sessions
      post :mass_update
      get :queue
      post :favorite
      get :last
      get :since
      get :activity
      get :download
    end
    
  end
  
  resources :repositories do
    
    collection do
      get :test
    end

  end

  resources :notes

  resources :users do
    collection do
      post :toggle_settings
      post :remove
      post :add
    end
  end

  resources :page do
    collection do
      get :search
      get :results
    end
  end

end

snorby/app/views/page/_cpu_state.html.erb
<% content_for :footer do %>
  <script type="text/javascript">
    $(function () {

      $('#cpu_state').highcharts(Highcharts.merge(gaugeOptions, {
        yAxis: {
            min: 0,
            max: 100,
            title: {
                text: '处理器'
            }
        },

        credits: {
            enabled: false
        },

        series: [{
            name: '处理器',
            data: [<%= @cpu %>],
            dataLabels: {
                format: '<div style="text-align:center"><span style="font-size:25px;color:' +
                    ((Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black') + '">{y}</span><br/>' +
                       '<span style="font-size:12px;color:silver">%</span></div>'
            },
            tooltip: {
                valueSuffix: '%'
            }
        }]
      }));
    });
  </script>
<% end %>
<div id='cpu_state' style='width:230px;height:150px;'></div>

snorby/app/views/page/_disk_state.html.erb
<% content_for :footer do %>
  <script type="text/javascript">
    $(function () {

      $('#disk_state').highcharts(Highcharts.merge(gaugeOptions, {
        yAxis: {
            min: 0,
            max: 100,
            title: {
                text: '磁盘'
            }
        },

        credits: {
            enabled: false
        },

        series: [{
            name: '磁盘',
            data: [<%= @disk %>],
            dataLabels: {
                format: '<div style="text-align:center"><span style="font-size:25px;color:' +
                    ((Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black') + '">{y}</span><br/>' +
                       '<span style="font-size:12px;color:silver">%</span></div>'
            },
            tooltip: {
                valueSuffix: '%'
            }
        }]
      }));
    });
  </script>
<% end %>
<div id='disk_state' style='width:230px;height:150px'></div>

snorby/app/views/page/_events.html.erb
<div id="events" class='grid_12 boxit' data-action='<%= params[:action] %>' data-page='<%= params[:page].to_i %>'>
	
	<%= form_tag mass_update_events_path do %>
	
	<%= hidden_field_tag :current_url, request.fullpath %>
	
	<%= hidden_field_tag :selected_events, [] %>
	
	<ul class='table'>
		
		<li class='header'>
			<div class='row <%= 'geoip' if geoip? %>'>
        <!--<div class='small'>
          <%= check_box_tag 'event-select-all', nil, false, :class => 'event-select-all' %>
        </div>-->
        
        <div class='small'>&nbsp;</div>
        
        <!--<div class='small'>
          <%= sortable(:sig_priority, 'Sev.')%>
        </div>-->
        
        <div class='address'>
          <%= sortable(:ip_src, '源IP')%>
        </div>
        
        <div class='address'>
          <%= sortable(:ip_dst, '目的IP')%>
        </div>
        
        <div class='signature'>
          <%= sortable(:sig_name, '事件特征')%>
        </div>
        
        <div class='timestamp'>
          <%= sortable(:timestamp, '时间')%>
        </div>

			</div>
		</li>

		
		<div class='content'>
			<%= render @events %>
		</div>
		
	</ul>
	
	<% end %>
	
	<%= pager(@events, request.fullpath) %>
	
</div>

snorby/app/views/page/_graph_destination_ips.html.erb
<% if @dst_metrics.empty? %>

	<div id='destination-ips-graph' style='display:none;' class='dashboard-graph no-pie-data'></div>

<% else %>

	<% content_for :footer do %>

		<script type="text/javascript">

		chart = new Highcharts.Chart({
		      chart: {
		         renderTo: 'destination-ips-graph',
		         margin: [90, 90, 90, 90]
		      },
          credits: {
            enabled: false
          },
		      title: {
		         text: ''
		      },
		      tooltip: {
		         formatter: function() {
		            return "<b>" + this.point.name.substring(0, 30) + "</b>... (共计" + this.y + ")"
		         }
		      },
		      plotOptions: {
		         pie: {
              events: {
                click: function(event) {
                  HCloader(event.target.nearestViewportElement.parentElement.id);
                  document.location = baseuri + '/results?title=目的IP地址 '+event.point.name+'&match_all=true&search%5B0%5D%5Bcolumn%5D=destination_ip&search'+
                    '%5B0%5D%5Benabled%5D=true&search%5B0%5D%5Boperator%'+
                    '5D=is&search%5B0%5D%5Bvalue%5D='+event.point.name+'&search%'+
                    '5B1%5D%5Bcolumn%5D=start_time&search%5B1%5D%5Benabl'+
                    'ed%5D=true&search%5B1%5D%5Boperator%5D=gte&search%5B'+
                    '1%5D%5Bvalue%5D=<%= @start_time.strftime("%Y-%m-%d %H:%M:%S") %>&search%5B2%5D%5B'+
                    'column%5D=end_time&search%5B2%5D%5Benabled%5D=true&'+
                    'search%5B2%5D%5Boperator%5D=lte&search%5B2%5D%5Bvalu'+
                    'e%5D=<%= @end_time.strftime("%Y-%m-%d %H:%M:%S") %>';
                 },
              },
		            allowPointSelect: true,
		            cursor: 'pointer',
								dataLabels: {
										distance: 20,
									  formatter: function() {
										return "" + this.point.name.substring(0, 30) + "... (" + Math.round(this.percentage) + "%)"
									 },
		                connectorColor: '#888',
										style: {
											fontSize: 10
										}
		            }
		         }
		      },
			    legend: {
			        enabled: false
			    },
		       series: [{
		         type: 'pie',
                         size: 300,
		         name: '特定目的IP地址',
		         data: [
							<% @dst_metrics.each do |key,value| %>
								['<%= key.to_s %>', <%= value %>],
							<% end %>
		         ]
		      }]
		   });

		</script>

	<% end %>

	<div id='destination-ips-graph' style='display:none;' class='dashboard-graph'></div>

<% end %>

snorby/app/views/page/_graph_event.html.erb
<% content_for :footer do %>

	<script type="text/javascript">
		
		chart = new Highcharts.Chart({
		      chart: {
		         renderTo: 'events-graph',
		         defaultSeriesType: 'spline',
		         marginRight: 80,
							marginLeft: 80,
							marginTop: 50,
		         marginBottom: 50
		      },
          credits: {
            enabled: false
          },
		      title: {
		         text: 'Event Count vs Time By Sensor',
		         x: -20 //center
		      },
		      xAxis: {
            categories: [<%= @axis.try(:html_safe) %>],
		        title: {
								margin: 10,
								<% if (@range == 'year' || @range == 'quarter') %>
									text: 'Month of Year'
								<% elsif (@range == 'month' || @range == 'last_month') %>
									text: 'Date of Month'
								<% elsif (@range == 'week' || @range == 'last_week') %>
									text: 'Date Of Week'
                <% elsif @range == 'last_24' %>
                  text: 'Last 24 Hours'
								<% else %>
									text: 'Hour of Day'
								<% end %>
		         }
		      },
		      yAxis: {
		         title: {
		            text: 'Event Count'
		         },
		         plotLines: [{
		            value: 0,
		            width: 1,
		            color: '#808080'
		         }]
		      },
		      tooltip: {
			       formatter: function() {
		                   return '<b>'+ this.series.name +'</b><br/>'+ this.y + ' Events';
		         }
	        },
		      legend: {
		         layout: 'vertical',
		         align: 'right',
		         verticalAlign: 'top',
		         x: 0,
		         y: 0,
		         borderWidth: 0,
						 borderRadius: 0,
						 borderColor: '#ddd',
						 backgroundColor: '#fff'
		      },
		      series: <%= @sensor_metrics.to_json.html_safe %>
		   });
		
		
	</script>

<% end %>

<div id='events-graph' class='dashboard-graph'></div>

snorby/app/views/page/_graph_protocol.html.erb
<% content_for :footer do %>

	<script type="text/javascript">
		
		chart = new Highcharts.Chart({
		      chart: {
		         renderTo: 'sb',
		         defaultSeriesType: 'spline',
		         marginRight: 80,
							marginLeft: 80,
							marginTop: 50,
		         marginBottom: 50
		      },
          credits: {
            enabled: false
          },
		      title: {
		         text: 'Protocol Count vs Time',
		         x: -20 //center
		      },
		      xAxis: {
          categories: [<%= @axis.try(:html_safe) %>],
		        title: {
								margin: 10,
								<% if (@range == 'year' || @range == 'quarter') %>
									text: 'Month of Year'
								<% elsif (@range == 'month' || @range == 'last_month') %>
									text: 'Date of Month'
								<% elsif (@range == 'week' || @range == 'last_week') %>
									text: 'Date Of Week'
                <% elsif @range == 'last_24' %>
                  text: 'Last 24 Hours'
								<% else %>
									text: 'Hour of Day'
								<% end %>
		         }
		      },
		      yAxis: {
		         title: {
		            text: 'Protocol Count'
		         },
		         plotLines: [{
		            value: 0,
		            width: 1,
		            color: '#808080'
		         }]
		      },
		      tooltip: {
		         formatter: function() {
		                   return '<b>'+ this.series.name +'</b><br/>'+ this.y + ' Events';
		         }
		      },
		      legend: {
		         layout: 'vertical',
		         align: 'right',
		         verticalAlign: 'top',
		         x: 0,
		         y: 0,
		         borderWidth: 0,
						 borderRadius: 0,
						 borderColor: '#ddd',
						 backgroundColor: '#fff'
		      },
		      series: [{
						name: 'TCP',
						data: [<%= @tcp.join(', ') %>]
					},{
						name: 'UDP',
						data: [<%= @udp.join(', ') %>]
					},{
						name: 'ICMP',
						data: [<%= @icmp.join(', ') %>]
					}]
		   });
		
		
	</script>

<% end %>

<div id='protocol-graph' style='display:none;' class='dashboard-graph'></div>

snorby/app/views/page/_graph_severity.html.erb
<% content_for :footer do %>

	<script type="text/javascript">
		
		chart = new Highcharts.Chart({
		      chart: {
		         renderTo: 'severity-graph',
		         defaultSeriesType: 'spline',
		         marginRight: 80,
							marginLeft: 80,
							marginTop: 50,
		         marginBottom: 50
		      },
          credits: {
            enabled: false
          },
		      title: {
		         text: 'Severity Count vs Time',
		         x: -20 //center
		      },
		      xAxis: {
            categories: [<%= @axis.try(:html_safe) %>],
		        title: {
								margin: 10,
								<% if (@range == 'year' || @range == 'quarter') %>
									text: 'Month of Year'
								<% elsif (@range == 'month' || @range == 'last_month') %>
									text: 'Date of Month'
								<% elsif (@range == 'week' || @range == 'last_week') %>
									text: 'Date Of Week'
                <% elsif @range == 'last_24' %>
                  text: 'Last 24 Hours'
								<% else %>
									text: 'Hour of Day'
								<% end %>
		         }
		      },
		      yAxis: {
		         title: {
		            text: 'Severity Count'
		         },
		         plotLines: [{
		            value: 0,
		            width: 1,
		            color: '#808080'
		         }]
		      },
		      tooltip: {
		         formatter: function() {
		                   return '<b>'+ this.series.name +'</b><br/>'+ this.y + ' Events';
		         }
		      },
		      legend: {
		         layout: 'vertical',
		         align: 'right',
		         verticalAlign: 'top',
		         x: 0,
		         y: 0,
		         borderWidth: 0,
						 borderRadius: 0,
						 borderColor: '#ddd',
						 backgroundColor: '#fff'
		      },
		      series: [{
            name: 'High Severity',
            color: sev1_bg_color,
						data: [<%= @high.join(', ') %>]
					},{
						name: 'Medium Severity',
            color: sev2_bg_color,
						data: [<%= @medium.join(', ') %>]
					},{
            name: 'Low Severity',
            color: sev3_bg_color,
						data: [<%= @low.join(', ') %>]
					}]
		   });
		
		
	</script>

<% end %>

<div id='severity-graph' style='display:none;' class='dashboard-graph'></div>

snorby/app/views/page/_graph_signature.html.erb
<% if @signature_metrics.empty? %>

	<div id='signature-graph' style='display:yes;' class='dashboard-graph no-pie-data'></div>

<% else %>

	<% content_for :footer do %>

		<script type="text/javascript">

		pie = new Highcharts.Chart({
		      chart: {
		         renderTo: 'signature-graph',
		         margin: [0, 0, 0, 0]
		      },
          credits: {
            enabled: false
          },
		      title: {
		         text: ''
		      },
		      tooltip: {
		         formatter: function() {
		            return "<b>" + this.point.name.substring(0, 30) + "</b>... (" + this.y + " 个事件)"
		         }
		      },
		      plotOptions: {
		         pie: {
              events: {
                click: function(event) {
                  HCloader(event.target.nearestViewportElement.parentElement.id);
                  document.location = baseuri + '/results?title='+event.point.name+'&match_all=true&search%5B0%5D%5Bcolumn%5D=signature_name&search'+
                    '%5B0%5D%5Benabled%5D=true&search%5B0%5D%5Boperator%'+
                    '5D=contains&search%5B0%5D%5Bvalue%5D='+event.point.name+'&search%'+
                    '5B1%5D%5Bcolumn%5D=start_time&search%5B1%5D%5Benabl'+
                    'ed%5D=true&search%5B1%5D%5Boperator%5D=gte&search%5B'+
                    '1%5D%5Bvalue%5D=<%= @start_time.strftime("%Y-%m-%d %H:%M:%S") %>&search%5B2%5D%5B'+
                    'column%5D=end_time&search%5B2%5D%5Benabled%5D=true&'+
                    'search%5B2%5D%5Boperator%5D=lte&search%5B2%5D%5Bvalu'+
                    'e%5D=<%= @end_time.strftime("%Y-%m-%d %H:%M:%S") %>';
                }
              },
		            allowPointSelect: true,
		            cursor: 'pointer',
								dataLabels: {
										distance: 20,
									  formatter: function() {
										return "" + this.point.name.substring(0, 30) + "... (" + Math.round(this.percentage) + "%)"
									 },
		                connectorColor: '#888',
										style: {
											fontSize: 10
										}
		            }
		         }
		      },
			    legend: {
			        enabled: false
			    },
		       series: [{
		         type: 'pie',
                         size: 300,
		         name: 'Signatures',
		         data: [
							<% @signature_metrics.each do |key,value| %>
								['<%= key.to_s %>', <%= value %>],
							<% end %>
		         ]
		      }]
		   });

		</script>

	<% end %>

	<div id='signature-graph' style='display:yes;' class='dashboard-graph'></div>

<% end %>

snorby/app/views/page/dashboard.html.erb
<% javascript :footer, 'sparkline', 'highcharts', 'highcharts-more', 'solid-gauge' %>

<%= title "概览" do %>

	<%= render :partial => 'page/menu' %>

<% end %>

<div id='dashboard' class=''>
	
	<div class='main grid_9'>
		
		<div class='dashboard-menu'>
			<ul>
	<% if Snorby::Jobs.caching? %>
					<% content_for :footer do %>
						<script type="text/javascript">
							setTimeout(function(){
								location.reload();
							},2000);
						</script>
					<% end %>
          <li class='right last-cache-time'>
            <i>正在刷新<%= image_tag('icons/pager.gif', :size => '16x11') %></i>
          </li>
				<% else %>
				

          <li class='right last-cache-time'>
            <% if @last_cache.present? %>
            <i>更新时间: <%= display_time(@last_cache, true) %></i>
            <% end %>
          </li>

	<!--<li><%= link_to "报表导出", dashboard_path(:range => params[:range] == 'today' ? 'now' : params[:range], :format => :pdf), nil, { :class => 'dashboard' } %></li>-->	

	<li><%= drop_down_item "刷新数据",force_cache_path , nil, {:class => 'force-cache-update'}  if Snorby::Worker.running? %>
		
		<% end %>

<!--    注释    <li class='<%= "active" if @range == 'last_24' %> add_tipsy' title="<%= time_range_title(:last_24) %>"><%= link_to "Last 24", dashboard_path(:range => :last_24) %></li>
				
        <li class='<%= "active" if @range == 'today' %> add_tipsy' title="<%= time_range_title(:today) %>"><%= link_to "Today", dashboard_path(:range => :today) %></li>
				
        <li class='<%= "active" if @range == 'yesterday' %> add_tipsy' title="<%= time_range_title(:yesterday) %>"><%= link_to "Yesterday", dashboard_path(:range => :yesterday) %></li>

        <% if @now.beginning_of_week.day == @now.day %>
          <li class='<%= "active" if @range == 'last_week' %> add_tipsy' title="<%= time_range_title(:last_week) %>"><%= link_to "Last Week", dashboard_path(:range => :last_week) %></li>
        <% else %>
          <li class='<%= "active" if @range == 'week' %> add_tipsy' title="<%= time_range_title(:week) %>"><%= link_to "This Week", dashboard_path(:range => :week) %></li>
        <% end %>
			  
        <% if @now.day == 1 %>
           <li class='<%= "active" if @range == 'last_month' %> add_tipsy' title="<%= time_range_title(:last_month) %>"><%= link_to "Last Month", dashboard_path(:range => :last_month) %></li>
        <% else %>
          <li class='<%= "active" if @range == 'month' %> add_tipsy' title="<%= time_range_title(:month) %>"><%= link_to "This Month", dashboard_path(:range => :month) %></li>
        <% end %>	
				
        <li class='<%= "active" if @range == 'quarter' %> add_tipsy' title="<%= time_range_title(:quarter) %>"><%= link_to "This Quarter", dashboard_path(:range => :quarter) %></li>
				
				<li class='<%= "active" if @range == 'year' %> add_tipsy' title="<%= time_range_title(:year) %>"><%= link_to "This Year", dashboard_path(:range => :year) %></li>注释-->
						

			</ul>

		</div>
		
		<!--<div id='box-holder'>
			<%= render 'severity_dashboard.html.erb' %> 
		</div>-->
                <div id='box-holder'>
                   <%= render 'sys_status.html.erb' %>
		</div>
		<div id="box-tabs">

			<ul id="box-menu">
			<!--	<li class='active'><%= link_to "Sensors", '#', :class => 'show_events_graph' %></li>
				<li><%= link_to "Severities", '#', :class => 'show_severities_graph' %></li>
				<li><%= link_to "Protocols", '#', :class => 'show_protocol_graph' %></li>-->
				<li class='active'><%= link_to "特征", '#', :class => 'show_signature_graph' %></li>
				<li><%= link_to "源IP", '#', :class => 'show_source_ips_graph' %></li>
				<li><%= link_to "目的IP", '#', :class => 'show_destination_ips_graph' %></li>
				
			</ul>

		</div>
		
		<%= render 'graph_dashboard.html.erb' %>
		
	</div>
	
	<div class='secondary grid_3 alpha'>
	
	<!--注释	<div class='dashboard-header'>
			<span>Top 5 Sensor</span>
		</div>
		
		<ul class='box-list'>
			<% @sensors.each do |sensor| %>

			<li><%= link_to truncate(sensor.sensor_name, :length => 30), results_path(:title => "#{sensor.sensor_name}", 
        "match_all"=>"true", "search"=>{"sensor"=>{"column"=>"sensor", "operator"=>"is", "value"=> sensor.sid } }), :title => sensor.sensor_name %> 

        <span>
          <%= number_with_delimiter (sensor.events_count.zero? ? Event.count(:sid => sensor.sid) : sensor.events_count) %>
        </span>
      </li>
			<% end %>
		</ul>
	
		<div class='dashboard-header'>
			<span>Top 5 Active Users</span>
		</div>
		
		<ul class='box-list'>
			<% @favers.each do |user| %>
			<li class='has-image'>
				<%= image_tag(get_gravatar_uri(user.email), :size => '16x16', :class => 'avatar-small') %> 
				<%= link_to truncate(user.name, :length => 30), results_path(:title => "#{truncate("Events Classified By " + user.name.to_s, :length => 60)}", 
                "match_all"=>"true", "search"=>{"user"=>{"column"=>"user", "operator"=>"is", "value"=> user.id } }), :title => user.name %> 
				<span><%= number_with_delimiter user.classify_count %></span>
			</li>
			<% end %>
		</ul>注释-->
                <!--<iframe id='state' src='/state' scrolling=no>
		</iframe>-->
		<!--系统运行状态-->
		<!--<div class='dashboard-header'>
			<span>系统运行状态</span>
		</div>
                <div id="sys_status">
		<ul class='box-list2'>
		   <li id="cpu_status">
			&nbsp&nbspCPU<%= css_chart(percentage_for(@cpu, 100)) %>
		   </li>

		   <li id="ram_status">
			&nbsp&nbspRAM<%= css_chart(percentage_for(@ram, 100)) %>
		   </li>	

		   <li id="disk_status">
			&nbsp&nbspDISK<%= css_chart(percentage_for(@disk, 100)) %>
		   </li>
			
		</ul>
	        </div>-->
		<div class='dashboard-header'>
			<span>最近5类特征</span>
		</div>
		
		<ul class='box-list'>
			<% @recent_events.each do |event| %>
        <li>
          <%= link_to truncate(event.signature.name, :length => 28), results_path(:title => "#{truncate(event.signature.name, :length => 40)}", 
                "match_all"=>"true", "search"=>{"sensor"=>{"column"=>"signature", "operator"=>"is", "value"=> event.signature.sig_id } }), :title => event.signature.name %> 
          <span>
            <%= number_with_delimiter (event.signature.events_count.zero? ? Event.count(:sig_id => event.signature.sig_id) : event.signature.events_count) %>
          </span>
        </li>
			<% end %>
		</ul>
	
		<div class='dashboard-header'>
			<span>事件分类统计</span>
		</div>
		
		<ul class='box-list'>
			<% @classifications.each do |classification| %>
			
        <li>
          <%= link_to truncate(classification.name, :length => 25), results_path(:title => "#{classification.name}", 
          "match_all"=>"true", "search"=>{"sensor"=>{"column"=>"classification", "operator"=>"is", "value"=> classification.id } }), :title => classification.name %> 
          <span><%= number_with_delimiter classification.events_count %></span>
      </li>
			<% end %>
		</ul>
	
	</div>
	
</div>

snorby/app/views/page/results.js.erb
$('div#events').replaceWith("<%= escape_javascript(render(:partial => 'page/events', :locals => { :events => @events })) %>");
$('div.content').fadeTo(500, 1);
Snorby.helpers.remove_click_events(false);
Snorby.helpers.recheck_selected_events();

$('#title-header i').html("<%= "#{pluralize(@events.pager.total, 'event')} found" %>");

$.scrollTo('#header', 500);
flash();

snorby/app/views/page/search.html.erb
<%= stylesheet 'jquery' %>
<%= javascript :header, 'daterangepicker' %>

<% content_for :footer do %>

  <script type="text/javascript">

    var rule = new SearchRule('<%= escape_javascript @json.html_safe %>');
    rule.searchUI({
      cssClass: "submit-search",
      buttonTitle: "搜索"
    });
rule.add();
rule.add();
rule.add();

	</script>

<% end %>

<%= title "搜索" do %>

	<%= drop_down_for('更多选项', 'icons/filter.png', 'options') do %>

    <%= drop_down_item "保存当前搜索条件", new_saved_search_path, nil, { :class => "snorbybox" } %>

    <%= drop_down_item "查看已保存搜索结果", saved_searches_path, nil %>

    <%= drop_down_item "重置搜索项", '#', nil, {:class => 'reset-search-form'} %>

	<% end %>

<% end %>