snorby/config/routes.rb
Snorby::Application.routes.draw do
  
  get "restart/index"
  get "network/show"

  resources :rules do
    collection do
    end
  end

  resources :tcpdumps do
    collection do
      
    end
  end

  resources :net_flows do
    collection do
    end
  end

  resources :logs do
    collection do
	get :export
        get :backup
	get :showbak
	get :recovery
	get :delete
	get :empty
    end
  end

  resources :lookups

  # This feature is not ready yet
  # resources :notifications

  resources :jobs do
    member do
      get :last_error
      get :handler
    end
  end

  resources :classifications

  devise_for :users, :path_names => { :sign_in => 'login', 
    :sign_out => 'logout', 
    :sign_up => 'register' }, :controllers => { 
      :registrations => "registrations",
      :sessions => "sessions", 
      :passwords => 'passwords'
    } do
    get "/login" => "devise/sessions#new"
    get '/logout', :to => "devise/sessions#destroy"
    get '/reset/password', :to => "devise/passwords#edit"
  end

  root :to => "page#dashboard"

  resources :sensors do


    collection do
      get :agent_list
    end
  end

  resources :settings do
    collection do
      get :restart_worker
      get :start_sensor_cache
      get :start_daily_cache
      get :start_geoip_update
      get :start_worker
      get :start_sys_status
    end
  end

  resources :signatures do

    collection do
      get :search
    end
    
  end

  resources :severities do
  end
  
  match '/restart', :controller => 'restart', :action => 'index'
  match '/restart/update', :controller => 'restart', :action => 'update'
  match '/time', :controller => 'time', :action => 'index'
  match '/time/update', :controller => 'time', :action => 'update'
  match '/time/get_time', :controller => 'time', :action => 'get_time'
  match '/network', :controller => 'network', :action => 'show'
  match '/network/edit', :controller => 'network', :action => 'edit'
  match '/network', :controller => 'network', :action => 'update'
  match '/dashboard', :controller => 'Page', :action => 'dashboard'
  match '/search', :controller => 'Page', :action => 'search'
  match '/results', :controller => 'Page', :action => 'results'
  match '/force/cache', :controller => "Page", :action => 'force_cache'
  match '/cache/status', :controller => "Page", :action => 'cache_status'
  match '/search/json', :controller => "Page", :action => 'search_json'
  match '/syslogconf/', :controller => "syslogconf", :action => 'index'
  match '/syslogconf/update', :controller => "syslogconf", :action => 'update'
  match '/tcpdump/start', :controller => "tcpdumps", :action => 'start'
  match '/tcpdump/stop', :controller => "tcpdumps", :action => 'stop'
  match '/tcpdump/sendfile', :controller => "tcpdumps", :action => 'sendfile'
 

  resources :saved_searches, :path => "/saved/searches" do
    
    collection do
      post :title
      post :update
    end

    member do
      get :view
      post :update
    end
  end

  match ':controller(/:action(/:sid/:cid))', :controller => 'Events'

  resources :asset_names do
    member do
      delete :remove
    end

    collection do
      post :add
      get :lookup
      post :bulk_upload
      get 'get_bulk_upload', action: :get_bulk_upload, as: 'get_bulk_upload'
    end
  end

  resources :events do
    
    resources :notes do
      
    end
    
    collection do
      get :sessions
      get :view
      get :create_mass_action
      post :mass_action
      get :create_email
      post :email
      get :hotkey
      post :export
      get :lookup
      get :rule
      get :packet_capture
      get :history
      post :classify
      post :classify_sessions
      post :mass_update
      get :queue
      post :favorite
      get :last
      get :since
      get :activity
      get :download
    end
    
  end
  
  resources :repositories do
    
    collection do
      get :test
    end

  end

  resources :notes

  resources :users do
    collection do
      post :toggle_settings
      post :remove
      post :add
    end
  end

  resources :page do
    collection do
      get :search
      get :results
    end
  end

end

snorby/app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_filter :require_administrative_privileges

  def index
    @jobs = Snorby::Jobs.find.all
    @process = Snorby::Worker.process
    respond_to do |format|
      format.html
      format.js
      format.xml  { render :xml => @jobs }
    end
  end

  def last_error
    @job = Snorby::Jobs.find.get(params[:id])
    render :layout => false
  end
  
  def handler
    @job = Snorby::Jobs.find.get(params[:id])
    render :layout => false
  end

  def show
    @job = Snorby::Jobs.find.get(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @job }
    end
  end

  def edit
    @job = Snorby::Jobs.find.get(params[:id])
  end

  def update
    @job = Snorby::Jobs.find.get(params[:id])

    respond_to do |format|
      if @job.update(params[:job])
        format.html { redirect_to(@job, :notice => 'Job was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @job.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @job = Snorby::Jobs.find.get(params[:id])
    if @job.blank?
      redirect_to jobs_url
    else
      if @job.handler.to_s.rindex("SysStatusJob")
        `echo "0" > #{Snorby::Jobs::SysStatusJob.thread}`#set sys_status_job to off
      end
      @job.destroy
      respond_to do |format|
        format.html { redirect_to(jobs_url) }
        format.xml  { head :ok }
      end
    end
    
  end
end

snorby/app/helpers/jobs_helper.rb
module JobsHelper
end

snorby/app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

snorby/app/views/jobs/_job.html.erb
<tr id='job_<%= job.id %>' class='job' data-job-id='<%= job.id %>' data-job-failed='<%= job.failed_at.blank? ? false : true %>'>
	<td class='id first'><%= job.id %></td>
	<td class='priority'><%= job.priority %></td>
	<td class='attempts'><%= job.attempts %></td>
	
	<% if ((job.run_at < Time.zone.now) && job.locked_at) %>
		<% if job.last_error %>
			<td class='run_at fail'>failed</td>
		<% else %>
			<td class='run_at currently_running'><%= image_tag('icons/pager.gif') %>(in progress)</td>
		<% end %>
	<% else %>
		<td class='run_at'><%= distance_of_time_in_words(Time.zone.now, Time.zone.parse(job.run_at.to_s)) %></td>
	<% end %>
	
	<td class='failed_at'><%= job.failed_at || 'N/A' %></td>
	<td class='last_error'><%= job.last_error.blank? ? 'N/A' : (link_to truncate(job.last_error, :length => 30, :omission => '...'), last_error_job_path(job), :class => 'snorbybox') %></td>
	<td style='width:240px;' class='handler'><%= link_to truncate(job.handler, :length => 30, :omission => '...'), handler_job_path(job), :class => 'view_job_handler' %></td>
	<td class='last'><%= link_to image_tag("icons/destroy.png", :size => '16x16', :class => 'trash'), job_path(job), :method => :delete, :confirm => "Are you sure you want to remove this job?" %></td>
</tr>

snorby/app/views/jobs/_jobs.html.erb
<div id="jobs" class='grid_12 page boxit'>	

	<table class='default' border="0" cellspacing="0" cellpadding="0">
	  <tr>
	    <th>ID</th>
	    <th>Pri.</th>
	    <th>Attempts</th>
			<th>Run At</th>
			<th>failed_at</th>
			<th>Last Error</th>
			<th>Handler</th>
			<th>&nbsp;</th>
	  </tr>

		<tbody class='content jobs'>
			<%= render :partial => 'jobs/job', :collection => @jobs %>
		</tbody>
		
	</table>

	<br />

</div>

snorby/app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

snorby/app/views/jobs/handler.html.erb
<%= snorby_box('Job Handler Data') do %>

	<div id='job-box-content' class=''>

		<pre id='handler'><%= @job.handler %></pre>

	</div>

<% end %>

snorby/app/views/jobs/index.html.erb
<%= title "Worker & Job Queue".html_safe do -%>

	<% if Snorby::Worker.running? %>
		<%= menu_item "Restart Worker", restart_worker_settings_path, 'icons/restart.png', :confirm => "Are you sure you want to restart the worker process?" %>
	<% end %>

	<%= render :partial => 'settings/menu' %>
	
<%- end -%>

<div id='snorby-worker' class='grid_12 page boxit'>
	
	<% if Snorby::Worker.running? %>

		<table class='default' border="0" cellspacing="0" cellpadding="0">

			<tr>
				<th>Status</th>
				<th class="user">user</th>
				<th class="pid">pid</th>
				<th class="created_at">created_at</th>
				<th class="runtime">runtime</th>
				<th class="command">command</th>
				<th class="cpu">cpu</th>
				<th class="memory">memory</th>
			</tr>

			<tbody class='content process'>
				<td class='first'>
					<%= worker_status %>
				</td>
				<td class="user"><%= @process.user %></td>
				<td class="pid"><%= @process.pid %></td>
				<td class="created_at"><%= @process.created_at %></td>
				<td class="runtime"><%= @process.runtime %></td>
				<td class="command"><%= truncate(@process.command, :length => 35, :omission => '...') %></td>
				<td class="cpu" style='width:200px'><%= css_chart(percentage_for(@process.cpu, 100)) %></td>
				<td class="memory last" style='width:200px'><%= css_chart(percentage_for(@process.memory, 100)) %></td>
			</tbody>

		</table>
		
		<div class='table-tooltip'></div>

	<% else %>

		<div id='note-box' class='error'>
			<%= image_tag('icons/note-icon-white.png') %>
			The Snorby worker is not currently running. It's imperative you start the worker immediately!
			All backend calculations are performed asynchronously using the Snorby Worker.
		</div>

	<% end %>
	
</div>

<%= render :partial => 'jobs/jobs' %>

snorby/app/views/jobs/last_error.html.erb
<%= snorby_box('Job Last Error') do %>

	<div id='job-box-content' class=''>

		<pre id='last_error'><%= @job.last_error %></pre>

	</div>

<% end %>

snorby/app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

snorby/app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>